use std::path::{Path, PathBuf};

/// The editor package's chrome metrics, relative to this build script.
///
/// The toolbar's minimum width is a property of the toolbar, and the window
/// this app builds may not open narrower than it. Reading the number here is
/// what keeps the Rust floor and the CSS `min-width` from being two independent
/// copies of one constraint: `packages/editor/chrome.json` is the only place it
/// is written down, `packages/editor/src/chrome.ts` exports it to the toolbar,
/// and this emits it for `editor.rs`. JSON rather than the TypeScript, because
/// a build script can parse the one and must not guess at the other.
const CHROME_JSON: &str = "../../../packages/editor/chrome.json";

/// Emits `chrome.rs` into `OUT_DIR` with the metrics `editor.rs` includes.
///
/// A missing or malformed file is a hard failure rather than a default: a
/// silent fallback would put the window floor back to being a number nobody
/// checks, which is the thing this exists to prevent.
fn emit_chrome_metrics() {
    println!("cargo:rerun-if-changed={CHROME_JSON}");

    let source = Path::new(env!("CARGO_MANIFEST_DIR")).join(CHROME_JSON);
    let text = std::fs::read_to_string(&source)
        .unwrap_or_else(|error| panic!("{} could not be read: {error}", source.display()));
    let metrics: serde_json::Value = serde_json::from_str(&text)
        .unwrap_or_else(|error| panic!("{} is not valid JSON: {error}", source.display()));
    let toolbar_min_width = metrics
        .get("toolbarMinWidth")
        .and_then(serde_json::Value::as_f64)
        .unwrap_or_else(|| panic!("{} has no numeric `toolbarMinWidth`", source.display()));

    let out = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"))
        .join("chrome.rs");
    std::fs::write(
        &out,
        format!(
            "// Generated by build.rs from {CHROME_JSON}. Do not edit.\n\
             /// The narrowest the editor's toolbar can be laid out at, in points.\n\
             const TOOLBAR_MIN_WIDTH: f64 = {toolbar_min_width:?};\n"
        ),
    )
    .unwrap_or_else(|error| panic!("{} could not be written: {error}", out.display()));
}

fn main() {
    emit_chrome_metrics();

    // The screencapturekit Swift bridge links against the Swift runtime, so
    // every binary that pulls `snapdeck-capture` in needs an rpath to it. A
    // `rustc-link-arg` applies only to the artifacts of the package whose build
    // script emitted it (its bins, cdylibs, examples, tests and benches) and is
    // not propagated to any dependent, so the rpath has to be re-declared by
    // each crate that links the bridge. Without it this app aborts before
    // `main` with `Library not loaded: @rpath/libswift_Concurrency.dylib`.
    // `crates/capture/build.rs` carries the identical line for that crate's own
    // test binaries: the duplication is deliberate, do not deduplicate it.
    // `/usr/lib/swift` is served from the dyld shared cache, not from disk.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        println!("cargo:rustc-link-arg=-Wl,-rpath,/usr/lib/swift");
    }

    tauri_build::build()
}
