export {
  BRIDGE_PORT,
  CLOSE_POLICY_VIOLATION,
  EXTENSION_ORIGIN_PREFIX,
  MAX_CLIENT_NAME_CHARS,
  MAX_CLIENT_VERSION_CHARS,
  MAX_DEVICE_PIXEL_RATIO,
  MAX_ERROR_MESSAGE_CHARS,
  MAX_HANDSHAKE_MESSAGE_BYTES,
  MAX_IMAGE_PIXELS,
  MAX_MESSAGE_BYTES,
  MAX_PNG_BASE64_CHARS,
  MAX_PNG_BYTES,
  MAX_REQUEST_ID_CHARS,
  MAX_SAVED_PATH_CHARS,
  MAX_TITLE_CHARS,
  MAX_TOKEN_CHARS,
  MAX_URL_CHARS,
  NONCE_HEX_LENGTH,
  PROOF_HEX_LENGTH,
  PROTOCOL_VERSION,
  REQUEST_ID_PATTERN,
} from './limits'
export {
  acceptedSchema,
  clientMessageSchema,
  encode,
  errorCodeSchema,
  errorMessageSchema,
  fullPageSchema,
  helloSchema,
  parseClientMessage,
  parseServerMessage,
  ProtocolError,
  readySchema,
  serverMessageSchema,
} from './messages'
export type {
  ClientMessage,
  ErrorCode,
  FullPage,
  Hello,
  ServerMessage,
} from './messages'
